//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisimPlus.resources.de {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class analyze {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal analyze() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogisimPlus.resources.de.analyze", typeof(analyze).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kombinatorik.
        /// </summary>
        internal static string analyzerWindowTitle {
            get {
                return ResourceManager.GetString("analyzerWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %s ist keine Eingangsvariable..
        /// </summary>
        internal static string badVariableName {
            get {
                return ResourceManager.GetString("badVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schaltung aufbauen.
        /// </summary>
        internal static string buildCircuitButton {
            get {
                return ResourceManager.GetString("buildCircuitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, daß Sie die Schaltung %s ersetzen möchten?.
        /// </summary>
        internal static string buildConfirmReplaceMessage {
            get {
                return ResourceManager.GetString("buildConfirmReplaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ersetzen bestätigen.
        /// </summary>
        internal static string buildConfirmReplaceTitle {
            get {
                return ResourceManager.GetString("buildConfirmReplaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konnte Schaltung nicht aufbauen.
        /// </summary>
        internal static string buildDialogErrorTitle {
            get {
                return ResourceManager.GetString("buildDialogErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schaltung aufbauen.
        /// </summary>
        internal static string buildDialogTitle {
            get {
                return ResourceManager.GetString("buildDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schaltungsname:.
        /// </summary>
        internal static string buildNameLabel {
            get {
                return ResourceManager.GetString("buildNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nur NAND-Gatter.
        /// </summary>
        internal static string buildNandsLabel {
            get {
                return ResourceManager.GetString("buildNandsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte einen Schaltungsnamen angeben..
        /// </summary>
        internal static string buildNeedCircuitError {
            get {
                return ResourceManager.GetString("buildNeedCircuitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte ein Zielprojekt angeben..
        /// </summary>
        internal static string buildNeedProjectError {
            get {
                return ResourceManager.GetString("buildNeedProjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zielprojekt:.
        /// </summary>
        internal static string buildProjectLabel {
            get {
                return ResourceManager.GetString("buildProjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nur Gatter mit zwei Eingängen.
        /// </summary>
        internal static string buildTwoInputsLabel {
            get {
                return ResourceManager.GetString("buildTwoInputsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konflikt mit den Ausgangswerten der Schaltung..
        /// </summary>
        internal static string busError {
            get {
                return ResourceManager.GetString("busError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Inhalt der Zwischenablage ist länger als die Tabelle..
        /// </summary>
        internal static string clipPasteEndError {
            get {
                return ResourceManager.GetString("clipPasteEndError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Einfügen.
        /// </summary>
        internal static string clipPasteErrorTitle {
            get {
                return ResourceManager.GetString("clipPasteErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Einfügebereich muß die gleiche Länge wie die Zwischenablage aufweisen..
        /// </summary>
        internal static string clipPasteSizeError {
            get {
                return ResourceManager.GetString("clipPasteSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Inhalt der Zwischenablage konnte nicht eingefügt werden..
        /// </summary>
        internal static string clipPasteSupportedError {
            get {
                return ResourceManager.GetString("clipPasteSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string exprClearButton {
            get {
                return ResourceManager.GetString("exprClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingabetaste.
        /// </summary>
        internal static string exprEnterButton {
            get {
                return ResourceManager.GetString("exprEnterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (leer).
        /// </summary>
        internal static string expressionEmpty {
            get {
                return ResourceManager.GetString("expressionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausdruck.
        /// </summary>
        internal static string expressionTab {
            get {
                return ResourceManager.GetString("expressionTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logische Ausdrücke ansehen und bearbeiten..
        /// </summary>
        internal static string expressionTabTip {
            get {
                return ResourceManager.GetString("expressionTabTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurücknehmen.
        /// </summary>
        internal static string exprRevertButton {
            get {
                return ResourceManager.GetString("exprRevertButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Implizites AND).
        /// </summary>
        internal static string implicitAndOperator {
            get {
                return ResourceManager.GetString("implicitAndOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingänge.
        /// </summary>
        internal static string inputsTab {
            get {
                return ResourceManager.GetString("inputsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingangsvariablen ansehen und bearbeiten..
        /// </summary>
        internal static string inputsTabTip {
            get {
                return ResourceManager.GetString("inputsTabTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekanntes Zeichen: %s.
        /// </summary>
        internal static string invalidCharacterError {
            get {
                return ResourceManager.GetString("invalidCharacterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Ausgang ausgewählt..
        /// </summary>
        internal static string karnaughNoOutputError {
            get {
                return ResourceManager.GetString("karnaughNoOutputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zu viele Eingänge für die Tabelle..
        /// </summary>
        internal static string karnaughTooManyInputsError {
            get {
                return ResourceManager.GetString("karnaughTooManyInputsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine passende öffnende Klammer..
        /// </summary>
        internal static string lparenMissingError {
            get {
                return ResourceManager.GetString("lparenMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als Ausdruck festlegen.
        /// </summary>
        internal static string minimizedSetButton {
            get {
                return ResourceManager.GetString("minimizedSetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimierung.
        /// </summary>
        internal static string minimizedTab {
            get {
                return ResourceManager.GetString("minimizedTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die kleinstmöglichen Ausdrücke ansehen und bearbeiten..
        /// </summary>
        internal static string minimizedTabTip {
            get {
                return ResourceManager.GetString("minimizedTabTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlender linker Operand für Operator %s..
        /// </summary>
        internal static string missingLeftOperandError {
            get {
                return ResourceManager.GetString("missingLeftOperandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlender rechter Operand für Operator %s..
        /// </summary>
        internal static string missingRightOperandError {
            get {
                return ResourceManager.GetString("missingRightOperandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schaltung schwingt..
        /// </summary>
        internal static string oscillateError {
            get {
                return ResourceManager.GetString("oscillateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgang:.
        /// </summary>
        internal static string outputSelectLabel {
            get {
                return ResourceManager.GetString("outputSelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgänge.
        /// </summary>
        internal static string outputsTab {
            get {
                return ResourceManager.GetString("outputsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgangsvariablen ansehen und bearbeiten..
        /// </summary>
        internal static string outputsTabTip {
            get {
                return ResourceManager.GetString("outputsTabTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schaltung ersetzen.
        /// </summary>
        internal static string replaceCircuitAction {
            get {
                return ResourceManager.GetString("replaceCircuitAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine passende schließende Klammer..
        /// </summary>
        internal static string rparenMissingError {
            get {
                return ResourceManager.GetString("rparenMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (leere Tabelle).
        /// </summary>
        internal static string tableEmptyMessage {
            get {
                return ResourceManager.GetString("tableEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (keine).
        /// </summary>
        internal static string tableNullHeader {
            get {
                return ResourceManager.GetString("tableNullHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelle.
        /// </summary>
        internal static string tableTab {
            get {
                return ResourceManager.GetString("tableTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wahrheitstabelle ansehen und bearbeiten..
        /// </summary>
        internal static string tableTabTip {
            get {
                return ResourceManager.GetString("tableTabTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        internal static string variableAddButton {
            get {
                return ResourceManager.GetString("variableAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Variable gleichen namens besteht bereits..
        /// </summary>
        internal static string variableDuplicateError {
            get {
                return ResourceManager.GetString("variableDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Maximale Größe von %s erreicht.).
        /// </summary>
        internal static string variableMaximumError {
            get {
                return ResourceManager.GetString("variableMaximumError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach unten.
        /// </summary>
        internal static string variableMoveDownButton {
            get {
                return ResourceManager.GetString("variableMoveDownButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach oben.
        /// </summary>
        internal static string variableMoveUpButton {
            get {
                return ResourceManager.GetString("variableMoveUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Name darf &apos;%s&apos; nicht enthalten..
        /// </summary>
        internal static string variablePartError {
            get {
                return ResourceManager.GetString("variablePartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entfernen.
        /// </summary>
        internal static string variableRemoveButton {
            get {
                return ResourceManager.GetString("variableRemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umbenennen.
        /// </summary>
        internal static string variableRenameButton {
            get {
                return ResourceManager.GetString("variableRenameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name muß mit einem Buchstaben anfangen..
        /// </summary>
        internal static string variableStartError {
            get {
                return ResourceManager.GetString("variableStartError", resourceCulture);
            }
        }
    }
}
