//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisimPlus.resources.de {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class circuit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal circuit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogisimPlus.resources.de.circuit", typeof(circuit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstelle eine Wahrheitstabelle für den Ausdruck, aufgrund von %s..
        /// </summary>
        internal static string analyzeCannotHandleError {
            get {
                return ResourceManager.GetString("analyzeCannotHandleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zirkelbezug entdeckt; erstelle stattdessen eine Wahrheitstabelle..
        /// </summary>
        internal static string analyzeCircularError {
            get {
                return ResourceManager.GetString("analyzeCircularError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konflikt mit den Ausgängen entdeckt; erstelle stattdessen eine Wahrheitstabelle..
        /// </summary>
        internal static string analyzeConflictError {
            get {
                return ResourceManager.GetString("analyzeConflictError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbolausrichtung.
        /// </summary>
        internal static string appearanceFacingAttr {
            get {
                return ResourceManager.GetString("appearanceFacingAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anker.
        /// </summary>
        internal static string circuitAnchor {
            get {
                return ResourceManager.GetString("circuitAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausrichtung der Beschriftung.
        /// </summary>
        internal static string circuitLabelDirAttr {
            get {
                return ResourceManager.GetString("circuitLabelDirAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schaltungsname.
        /// </summary>
        internal static string circuitName {
            get {
                return ResourceManager.GetString("circuitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string circuitPort {
            get {
                return ResourceManager.GetString("circuitPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a,b,c,d,e,f,g,h.
        /// </summary>
        internal static string defaultInputLabels {
            get {
                return ResourceManager.GetString("defaultInputLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x,y,z,u,v,w,s,t.
        /// </summary>
        internal static string defaultOutputLabels {
            get {
                return ResourceManager.GetString("defaultOutputLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dezimal mit Vorzeichen.
        /// </summary>
        internal static string radix10Signed {
            get {
                return ResourceManager.GetString("radix10Signed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dezimal ohne Vorzeichen.
        /// </summary>
        internal static string radix10Unsigned {
            get {
                return ResourceManager.GetString("radix10Unsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexadezimal.
        /// </summary>
        internal static string radix16 {
            get {
                return ResourceManager.GetString("radix16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binär.
        /// </summary>
        internal static string radix2 {
            get {
                return ResourceManager.GetString("radix2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oktal.
        /// </summary>
        internal static string radix8 {
            get {
                return ResourceManager.GetString("radix8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basis.
        /// </summary>
        internal static string radixAttr {
            get {
                return ResourceManager.GetString("radixAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit %s.
        /// </summary>
        internal static string splitterBitAttr {
            get {
                return ResourceManager.GetString("splitterBitAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine.
        /// </summary>
        internal static string splitterBitNone {
            get {
                return ResourceManager.GetString("splitterBitNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitbreite.
        /// </summary>
        internal static string splitterBitWidthAttr {
            get {
                return ResourceManager.GetString("splitterBitWidthAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemeinsame Seite des Verteilers.
        /// </summary>
        internal static string splitterCombinedTip {
            get {
                return ResourceManager.GetString("splitterCombinedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verteiler.
        /// </summary>
        internal static string splitterComponent {
            get {
                return ResourceManager.GetString("splitterComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausfächerung.
        /// </summary>
        internal static string splitterFanOutAttr {
            get {
                return ResourceManager.GetString("splitterFanOutAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Bits von der gemeinsamen Seite.
        /// </summary>
        internal static string splitterSplit0Tip {
            get {
                return ResourceManager.GetString("splitterSplit0Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit %s der gemeinsamen Seite.
        /// </summary>
        internal static string splitterSplit1Tip {
            get {
                return ResourceManager.GetString("splitterSplit1Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bits %s der gemeinsamen Seite.
        /// </summary>
        internal static string splitterSplitManyTip {
            get {
                return ResourceManager.GetString("splitterSplitManyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %s Teilschaltung.
        /// </summary>
        internal static string subcircuitCircuitTip {
            get {
                return ResourceManager.GetString("subcircuitCircuitTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %s ansehen.
        /// </summary>
        internal static string subcircuitViewItem {
            get {
                return ResourceManager.GetString("subcircuitViewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schaltung ändern.
        /// </summary>
        internal static string unknownChangeAction {
            get {
                return ResourceManager.GetString("unknownChangeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leitung.
        /// </summary>
        internal static string wireComponent {
            get {
                return ResourceManager.GetString("wireComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richtung.
        /// </summary>
        internal static string wireDirectionAttr {
            get {
                return ResourceManager.GetString("wireDirectionAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string wireDirectionHorzOption {
            get {
                return ResourceManager.GetString("wireDirectionHorzOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertikal.
        /// </summary>
        internal static string wireDirectionVertOption {
            get {
                return ResourceManager.GetString("wireDirectionVertOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Länge.
        /// </summary>
        internal static string wireLengthAttr {
            get {
                return ResourceManager.GetString("wireLengthAttr", resourceCulture);
            }
        }
    }
}
