//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisimPlus.resources.de {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogisimPlus.resources.de.files", typeof(files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schaltung hinzufügen.
        /// </summary>
        internal static string addCircuitAction {
            get {
                return ResourceManager.GetString("addCircuitAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name des Attributs fehlt.
        /// </summary>
        internal static string attrNameMissingError {
            get {
                return ResourceManager.GetString("attrNameMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wert des Attributs (%s) ist ungültig für %s.
        /// </summary>
        internal static string attrValueInvalidError {
            get {
                return ResourceManager.GetString("attrValueInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fehlender Schaltungsname.
        /// </summary>
        internal static string circNameMissingError {
            get {
                return ResourceManager.GetString("circNameMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bauteil `%s&apos; fehlt in der Bibliothek `%s&apos;.
        /// </summary>
        internal static string compAbsentError {
            get {
                return ResourceManager.GetString("compAbsentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position von Bauteil `%s&apos; ist ungültig (%s).
        /// </summary>
        internal static string compLocInvalidError {
            get {
                return ResourceManager.GetString("compLocInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position von Bauteil `%s&apos; ist nicht angegeben.
        /// </summary>
        internal static string compLocMissingError {
            get {
                return ResourceManager.GetString("compLocMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fehlende Bauteilbezeichnung.
        /// </summary>
        internal static string compNameMissingError {
            get {
                return ResourceManager.GetString("compNameMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bauteil `%s&apos; nicht gefunden.
        /// </summary>
        internal static string compUnknownError {
            get {
                return ResourceManager.GetString("compUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbenannt.
        /// </summary>
        internal static string defaultProjectName {
            get {
                return ResourceManager.GetString("defaultProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Laden von Element %s.
        /// </summary>
        internal static string fileAppearanceError {
            get {
                return ResourceManager.GetString("fileAppearanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element %s nicht gefunden.
        /// </summary>
        internal static string fileAppearanceNotFound {
            get {
                return ResourceManager.GetString("fileAppearanceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die eingebaute Bibliothek %s ist in dieser Version nicht verfügbar..
        /// </summary>
        internal static string fileBuiltinMissingError {
            get {
                return ResourceManager.GetString("fileBuiltinMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zirkelbezug kann nicht hergestellt werden. (Die Datei wird von der Bibliothek `%s&apos; benutzt.).
        /// </summary>
        internal static string fileCircularError {
            get {
                return ResourceManager.GetString("fileCircularError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannter Bibliotheksdeskriptor %s.
        /// </summary>
        internal static string fileDescriptorError {
            get {
                return ResourceManager.GetString("fileDescriptorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deskriptor für %s nicht bekannt..
        /// </summary>
        internal static string fileDescriptorUnknownError {
            get {
                return ResourceManager.GetString("fileDescriptorUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Kopieren der Datei: %s.
        /// </summary>
        internal static string fileDuplicateError {
            get {
                return ResourceManager.GetString("fileDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateifehler.
        /// </summary>
        internal static string fileErrorTitle {
            get {
                return ResourceManager.GetString("fileErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswählen.
        /// </summary>
        internal static string fileLibraryMissingButton {
            get {
                return ResourceManager.GetString("fileLibraryMissingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die erforderliche Bibliotheksdatei `%s&apos; fehlt. Bitte wählen Sie die Datei im folgenden Dialogfenster aus..
        /// </summary>
        internal static string fileLibraryMissingError {
            get {
                return ResourceManager.GetString("fileLibraryMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `%s&apos; lokalisieren..
        /// </summary>
        internal static string fileLibraryMissingTitle {
            get {
                return ResourceManager.GetString("fileLibraryMissingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer hat das Laden abgebrochen. [1].
        /// </summary>
        internal static string fileLoadCanceledError {
            get {
                return ResourceManager.GetString("fileLoadCanceledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateinachricht.
        /// </summary>
        internal static string fileMessageTitle {
            get {
                return ResourceManager.GetString("fileMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kann Datei `%s&apos; nicht schließen..
        /// </summary>
        internal static string fileSaveCloseError {
            get {
                return ResourceManager.GetString("fileSaveCloseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kann Datei `%s&apos; nicht speichern..
        /// </summary>
        internal static string fileSaveError {
            get {
                return ResourceManager.GetString("fileSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kann Datei nicht speichern.
        /// </summary>
        internal static string fileSaveErrorTitle {
            get {
                return ResourceManager.GetString("fileSaveErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Logisim-Bibliothek hat einen unbekannten Typ %s (%s).
        /// </summary>
        internal static string fileTypeError {
            get {
                return ResourceManager.GetString("fileTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler bei undefinierten Eingängen.
        /// </summary>
        internal static string gateUndefinedError {
            get {
                return ResourceManager.GetString("gateUndefinedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefinierte Eingänge ignorieren.
        /// </summary>
        internal static string gateUndefinedIgnore {
            get {
                return ResourceManager.GetString("gateUndefinedIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gatterausgang bei undefiniertem Zustand.
        /// </summary>
        internal static string gateUndefinedOption {
            get {
                return ResourceManager.GetString("gateUndefinedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Klasse %s konnte nicht in der JAR-Datei gefunden werden..
        /// </summary>
        internal static string jarClassNotFoundError {
            get {
                return ResourceManager.GetString("jarClassNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `%s&apos; ist kein gültiger Name einer Bibliothek..
        /// </summary>
        internal static string jarClassNotLibraryError {
            get {
                return ResourceManager.GetString("jarClassNotLibraryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java-Archiv (*.jar).
        /// </summary>
        internal static string jarFileFilter {
            get {
                return ResourceManager.GetString("jarFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Bibliothek %s konnte nicht instanziiert werden..
        /// </summary>
        internal static string jarLibraryNotCreatedError {
            get {
                return ResourceManager.GetString("jarLibraryNotCreatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die JAR-Datei konnte nicht geöffnet werden..
        /// </summary>
        internal static string jarNotOpenedError {
            get {
                return ResourceManager.GetString("jarNotOpenedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kein Bibliotheksdeskriptor angegeben.
        /// </summary>
        internal static string libDescMissingError {
            get {
                return ResourceManager.GetString("libDescMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibliothek `%s&apos; nicht gefunden.
        /// </summary>
        internal static string libMissingError {
            get {
                return ResourceManager.GetString("libMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kein Bibliotheksname angegeben.
        /// </summary>
        internal static string libNameMissingError {
            get {
                return ResourceManager.GetString("libNameMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibliotheken laden.
        /// </summary>
        internal static string loadLibrariesAction {
            get {
                return ResourceManager.GetString("loadLibrariesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibliothek laden.
        /// </summary>
        internal static string loadLibraryAction {
            get {
                return ResourceManager.GetString("loadLibraryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei %s enthält einen Verweis auf sich selbst..
        /// </summary>
        internal static string logisimCircularError {
            get {
                return ResourceManager.GetString("logisimCircularError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logisim-Projekt (*.circ).
        /// </summary>
        internal static string logisimFileFilter {
            get {
                return ResourceManager.GetString("logisimFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Öffnen von %s: %s.
        /// </summary>
        internal static string logisimLoadError {
            get {
                return ResourceManager.GetString("logisimLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifikator `%s&apos; zur Mausbelegung ungültig.
        /// </summary>
        internal static string mappingBadError {
            get {
                return ResourceManager.GetString("mappingBadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fehlender Modifikator zur Mausbelegung.
        /// </summary>
        internal static string mappingMissingError {
            get {
                return ResourceManager.GetString("mappingMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schaltungen neu anordnen.
        /// </summary>
        internal static string moveCircuitAction {
            get {
                return ResourceManager.GetString("moveCircuitAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schaltung entfernen.
        /// </summary>
        internal static string removeCircuitAction {
            get {
                return ResourceManager.GetString("removeCircuitAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voreinstellungen wieder herstellen.
        /// </summary>
        internal static string revertDefaultsAction {
            get {
                return ResourceManager.GetString("revertDefaultsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauptschaltung festlegen.
        /// </summary>
        internal static string setMainCircuitAction {
            get {
                return ResourceManager.GetString("setMainCircuitAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulationsgrenze.
        /// </summary>
        internal static string simLimitOption {
            get {
                return ResourceManager.GetString("simLimitOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zufälligkeit der Simulation.
        /// </summary>
        internal static string simRandomOption {
            get {
                return ResourceManager.GetString("simRandomOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fehlender Werkzeugname.
        /// </summary>
        internal static string toolNameMissingError {
            get {
                return ResourceManager.GetString("toolNameMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Datei bekannt, die %s entspricht..
        /// </summary>
        internal static string unknownLibraryFileError {
            get {
                return ResourceManager.GetString("unknownLibraryFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibliotheken entfernen.
        /// </summary>
        internal static string unloadLibrariesAction {
            get {
                return ResourceManager.GetString("unloadLibrariesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibliothek entfernen.
        /// </summary>
        internal static string unloadLibraryAction {
            get {
                return ResourceManager.GetString("unloadLibraryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibliothek enthält Elemente, die mit der Maus verknüpft sind..
        /// </summary>
        internal static string unloadMappingError {
            get {
                return ResourceManager.GetString("unloadMappingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibliothek enthält Elemente auf der Werkzeugleiste..
        /// </summary>
        internal static string unloadToolbarError {
            get {
                return ResourceManager.GetString("unloadToolbarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schaltung &apos;%s&apos; verwendet Elemente der Bibliothek..
        /// </summary>
        internal static string unloadUsedError {
            get {
                return ResourceManager.GetString("unloadUsedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ende der Leitung hat falsches Format.
        /// </summary>
        internal static string wireEndInvalidError {
            get {
                return ResourceManager.GetString("wireEndInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ende der Leitung nicht definiert.
        /// </summary>
        internal static string wireEndMissingError {
            get {
                return ResourceManager.GetString("wireEndMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anfang der Leitung hat falsches Format.
        /// </summary>
        internal static string wireStartInvalidError {
            get {
                return ResourceManager.GetString("wireStartInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anfang der Leitung nicht definiert.
        /// </summary>
        internal static string wireStartMissingError {
            get {
                return ResourceManager.GetString("wireStartMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interner Fehler beim Erstellen von XML.
        /// </summary>
        internal static string xmlConversionError {
            get {
                return ResourceManager.GetString("xmlConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim XML-Format: %s.
        /// </summary>
        internal static string xmlFormatError {
            get {
                return ResourceManager.GetString("xmlFormatError", resourceCulture);
            }
        }
    }
}
